server:
  port: 8080

spring:
  profiles:
    default: local
  config:
    import: classpath:config/secret.yml


---
spring:
  config:
    activate:
      on-profile: local
  security:
    user:
      password: password
      name: username
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error


---
spring:
  config:
    import: classpath:config/secret.yml
    activate:
      on-profile: test
  security:
    user:
      password: sa
      name:
  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error