server:
  port: 8080

spring:
  config:
    import: classpath:secret.yml

  security:
    user:
      password: password
      name: username

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error