server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realworlddb
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
